// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using upsideCakes.Data;

#nullable disable

namespace upsideCakes.Migrations
{
    [DbContext(typeof(UpsideCakesDbContext))]
    [Migration("20231001212503_update1")]
    partial class update1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("upsideCakes.Models.Pagamento", b =>
                {
                    b.Property<int>("_idPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("_data")
                        .HasColumnType("TEXT");

                    b.Property<string>("_formaDePagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("_valor")
                        .HasColumnType("REAL");

                    b.HasKey("_idPedido");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("upsideCakes.Models.Pessoa", b =>
                {
                    b.Property<string>("_cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("_nome")
                        .HasColumnType("TEXT");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("upsideCakes.Models.Produto", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_nome")
                        .HasColumnType("TEXT");

                    b.Property<float>("_preco")
                        .HasColumnType("REAL");

                    b.HasKey("_id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("upsideCakes.Models.Usuario", b =>
                {
                    b.Property<string>("_login")
                        .HasColumnType("TEXT");

                    b.Property<string>("_senha")
                        .HasColumnType("TEXT");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
