// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using upsideCakes.Data;

#nullable disable

namespace upsideCakes.Migrations
{
    [DbContext(typeof(UpsideCakesDbContext))]
    partial class UpsideCakesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("upsideCakes.Models.Funcionario", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_cpf")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("_dataNasc")
                        .HasColumnType("TEXT");

                    b.Property<string>("_email")
                        .HasColumnType("TEXT");

                    b.Property<string>("_endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("_nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("_telefone")
                        .HasColumnType("INTEGER");

                    b.HasKey("_id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("upsideCakes.Models.Gerente", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_cpf")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("_dataNasc")
                        .HasColumnType("TEXT");

                    b.Property<string>("_email")
                        .HasColumnType("TEXT");

                    b.Property<string>("_endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("_nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("_telefone")
                        .HasColumnType("INTEGER");

                    b.HasKey("_id");

                    b.ToTable("Gerente");
                });

            modelBuilder.Entity("upsideCakes.Models.Pagamento", b =>
                {
                    b.Property<int>("_idPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("_data")
                        .HasColumnType("TEXT");

                    b.Property<string>("_formaDePagamento")
                        .HasColumnType("TEXT");

                    b.Property<float>("_valor")
                        .HasColumnType("REAL");

                    b.HasKey("_idPedido");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("upsideCakes.Models.Produto", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_nome")
                        .HasColumnType("TEXT");

                    b.Property<float>("_preco")
                        .HasColumnType("REAL");

                    b.HasKey("_id");

                    b.ToTable("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
